const state={rows:[],filtered:[]};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'SAR',maximumFractionDigits:0}).format(n||0);
const num=n=>new Intl.NumberFormat('en-US').format(Math.round(n||0));
const pct=n=>(n||0).toFixed(1)+'%';
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;}else if(c==='"'){q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>x!==''))rows.push(row);row=[];}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row)}const h=rows.shift();return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
function cast(r){['RSP','TGM_Pct','Sales_Value','Profit_Value','Inventory_Value','Inventory_Risk_Value'].forEach(k=>r[k]=+r[k]);['Purchase_Qty','Sales_Qty','SOH','Is_Active'].forEach(k=>r[k]=+r[k]);return r}
async function loadDefault(){const t=await fetch('data/sample_pharmacy_products.csv').then(r=>r.text());setRows(parseCSV(t).map(cast))}
function setRows(rows){state.rows=rows;populateFilters();applyFilters()}
function unique(k){return [...new Set(state.rows.map(r=>r[k]))].sort()}
function fill(id,vals){const el=document.getElementById(id),cur=el.value;el.innerHTML='<option value="">All</option>'+vals.map(v=>`<option>${v}</option>`).join('');if(vals.includes(cur))el.value=cur}
function populateFilters(){fill('status',unique('Status'));fill('category',unique('Category'));fill('supplier',unique('Supplier_Name'));fill('price',unique('Price_Range'))}
function applyFilters(){const g=id=>document.getElementById(id).value;state.filtered=state.rows.filter(r=>(!g('status')||r.Status===g('status'))&&(!g('category')||r.Category===g('category'))&&(!g('supplier')||r.Supplier_Name===g('supplier'))&&(!g('price')||r.Price_Range===g('price')));render()}
function sum(k,a=state.filtered){return a.reduce((s,r)=>s+(+r[k]||0),0)}
function group(k,a=state.filtered){const m={};a.forEach(r=>(m[r[k]]??=[]).push(r));return m}
function kpi(id,val,note=''){document.querySelector(`#${id} .value`).textContent=val;document.querySelector(`#${id} .note`).textContent=note}
function bars(id,items,formatter=x=>num(x),cls=''){const el=document.getElementById(id);if(!items.length){el.innerHTML='<div class="empty">No data</div>';return}const mx=Math.max(...items.map(x=>x.value),1);el.innerHTML=items.map(x=>`<div class="bar-row"><div title="${x.name}">${x.name}</div><div class="track"><div class="bar ${cls}" style="width:${Math.max(2,x.value/mx*100)}%"></div></div><div>${formatter(x.value)}</div></div>`).join('')}
function render(){const a=state.filtered,active=a.filter(r=>r.Status==='Active'),blocked=a.filter(r=>r.Status==='Blocked'),zero=active.filter(r=>r.Sales_Qty===0);kpi('k-total',num(a.length),'Filtered SKUs');kpi('k-active',num(active.length),pct(a.length?active.length/a.length*100:0));kpi('k-blocked',num(blocked.length),pct(a.length?blocked.length/a.length*100:0));kpi('k-salesqty',num(sum('Sales_Qty')),'Units');kpi('k-sales',money(sum('Sales_Value')),'Synthetic sales value');kpi('k-profit',money(sum('Profit_Value')),'Synthetic profit value');kpi('k-tgm',pct(active.length?active.reduce((s,r)=>s+r.TGM_Pct,0)/active.length*100:0),'Active SKUs only');kpi('k-risk',money(zero.reduce((s,r)=>s+r.Inventory_Risk_Value,0)),`${num(zero.length)} Active zero-sales SKUs`);
const ap=a.length?active.length/a.length*100:0;document.getElementById('statusDonut').style.background=`conic-gradient(#2e7d32 0 ${ap}%, #98a2b3 ${ap}% 100%)`;document.getElementById('statusLegend').innerHTML=`<div><span class="dot a"></span>Active: <b>${num(active.length)}</b> (${pct(ap)})</div><div style="margin-top:8px"><span class="dot b"></span>Blocked: <b>${num(blocked.length)}</b></div>`;
let g=group('Category');bars('catSales',Object.entries(g).map(([name,rs])=>({name,value:rs.reduce((s,r)=>s+r.Sales_Value,0)})).sort((x,y)=>y.value-x.value),money);
bars('catTgm',Object.entries(g).map(([name,rs])=>{const ar=rs.filter(r=>r.Status==='Active');return{name,value:ar.length?ar.reduce((s,r)=>s+r.TGM_Pct,0)/ar.length*100:0}}).sort((x,y)=>y.value-x.value),pct,'green');
let zg=group('Category',zero);bars('zeroRisk',Object.entries(zg).map(([name,rs])=>({name,value:rs.reduce((s,r)=>s+r.Inventory_Risk_Value,0)})).sort((x,y)=>y.value-x.value),money,'amber');
const top=[...a].sort((x,y)=>y.Sales_Qty-x.Sales_Qty).slice(0,12);document.querySelector('#topTable tbody').innerHTML=top.map((r,i)=>`<tr><td>${i+1}</td><td>${r.SKU}</td><td>${r.Item_Name}</td><td>${r.Category}</td><td>${num(r.Sales_Qty)}</td><td>${money(r.Profit_Value)}</td></tr>`).join('');
const deps=[];const sg=group('Sub_Category',active);Object.entries(sg).forEach(([sub,rs])=>{const ss=[...new Set(rs.map(r=>r.Supplier_Name))];if(ss.length===1)deps.push({sub,supplier:ss[0],skus:rs.length,sales:rs.reduce((s,r)=>s+r.Sales_Qty,0)})});document.querySelector('#depTable tbody').innerHTML=deps.sort((x,y)=>y.skus-x.skus).map(r=>`<tr><td>${r.sub}</td><td><span class="pill">${r.supplier}</span></td><td>${num(r.skus)}</td><td>${num(r.sales)}</td></tr>`).join('')||'<tr><td colspan="4">No single-supplier dependency in current filter.</td></tr>';
const riskCat=Object.entries(zg).map(([name,rs])=>({name,value:rs.reduce((s,r)=>s+r.Inventory_Risk_Value,0)})).sort((x,y)=>y.value-x.value)[0];const salesCat=Object.entries(g).map(([name,rs])=>({name,value:rs.reduce((s,r)=>s+r.Sales_Value,0)})).sort((x,y)=>y.value-x.value)[0];document.getElementById('insights').innerHTML=[`<div class="insight"><b>Assortment:</b> ${num(active.length)} of ${num(a.length)} filtered SKUs are Active.</div>`,salesCat?`<div class="insight"><b>Category performance:</b> ${salesCat.name} leads Sales Value in the current filter.</div>`:'',riskCat?`<div class="insight"><b>Risk:</b> ${riskCat.name} has the highest Active zero-sales inventory-risk proxy.</div>`:'',`<div class="insight"><b>Dependency:</b> ${num(deps.length)} sub-categories are currently supplied by one supplier among Active SKUs.</div>`].join('')}
['status','category','supplier','price'].forEach(id=>document.getElementById(id).addEventListener('change',applyFilters));document.getElementById('csvfile').addEventListener('change',async e=>{const f=e.target.files[0];if(f)setRows(parseCSV(await f.text()).map(cast))});
loadDefault().catch(e=>{document.getElementById('insights').innerHTML='<div class="insight">Run via a local web server or upload a matching CSV file using the selector above.</div>';console.error(e)});
